apiVersion: v1
kind: Service
metadata:
  name: probe-example
  labels:
    app: probe-example
spec:
  ports:
  - name: rest
    nodePort: 30300
    port: 3000
    protocol: TCP
  selector:
    app: probe-example
  type: NodePort
