apiVersion: apps/v1
kind: Deployment
metadata:
  name: startup-pass
  labels:
    app: probe-example
spec:
  selector:
    matchLabels:
      app: probe-example
  template:
    metadata:
      labels:
        app: probe-example
    spec:
      containers:
      - name: app
        image: $REGISTRY/k8s-probe-example:0.1.0
        imagePullPolicy: Always
        ports:
        - name: rest
          containerPort: 3000
        env:
        - name: STARTUP_DURATION
          value: "30"
        startupProbe:
          httpGet:
            path: /livez
            port: rest
          failureThreshold: 6
          periodSeconds:  10
