apiVersion: apps/v1
kind: Deployment
metadata:
  name: startup-pass
  labels:
    app: prober
    mode: startup
spec:
  selector:
    matchLabels:
      app: startup-pass
  template:
    metadata:
      labels:
        app: startup-pass
        mode: startup
    spec:
      containers:
      - name: app
        image: $REGISTRY/k8s-probe-example:0.1.0
        ports:
        - name: rest
          containerPort: 3000
        env:
        - name: STARTUP_DURATION
          value: "30"
        startupProbe:
          httpGet:
            path: /livez
            port: rest
          failureThreshold: 6
          periodSeconds:  10
